server {
    listen 80;

    # Configurações de CORS para o seu Frontend React
    add_header 'Access-Control-Allow-Origin' 'http://127.0.0.1:5173' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
    add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;

    # Serviço de Quartos (Porta 8002)
    location /api/quartos/ {
        proxy_pass http://quarto-service:8002/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Serviço de Hóspedes (Porta 8001)
    location /api/hospedes/ {
        proxy_pass http://hospede-service:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Serviço de Reservas (Porta 8003)
    location /api/reserva/ {
        proxy_pass http://reserva-service:8003/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Serviço de Hospedagem (Porta 8004)
    location /api/hospedagens/ {
        proxy_pass http://hospedagem-service:8004/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Serviço de Limpeza (Porta 8005)
    location /api/limpezas/ {
        proxy_pass http://limpeza-service:8005/;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}